GET http://localhost:5255/games

###
GET http://localhost:5255/games/1

###
POST http://localhost:5255/games
Content-Type: application/json

{
    "name" : "FIFA 24",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "2023-10-01"
}

###
PUT http://localhost:5255/games/1
Content-Type: application/json

{
    "name": "FIFA 25",
    "genreId": 5,
    "price": 29.99,
    "releaseDate": "2024-01-01"
}

###
DELETE http://localhost:5255/games/1