GET http://localhost:5255/games

###
GET http://localhost:5255/games/1

###
POST http://localhost:5255/games
Content-Type: application/json

{
     
    "genre": "Sports",
    "price": 19.99,
    "releaseDate": "2023-10-01"
}


###
PUT http://localhost:5255/games/2
Content-Type: application/json

{

    "genre": "Moba",
    "price": 1.25,
    "releaseDate": "2024-01-01"
}

###
DELETE http://localhost:5255/games/3